"""add_roles_and_users_tables

Revision ID: bf75305a1a5e
Revises: 23b80e7dc694
Create Date: 2026-08-25 14:56:26.352878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.enums import UserRoleEnum


# revision identifiers, used by Alembic.
revision: str = 'bf75305a1a5e'
down_revision: Union[str, Sequence[str], None] = '23b80e7dc694'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'roles', ['name'])
    # ### end Alembic commands ###

    roles_table = sa.table(
                    "roles",
                    sa.column("name", sa.String)
                  )

    op.bulk_insert(
        roles_table,
        [
            {'name': UserRoleEnum.ADMIN.value},
            {'name': UserRoleEnum.WORKER.value},
            {'name': UserRoleEnum.MANAGER.value},
        ]
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'roles', type_='unique')
    # ### end Alembic commands ###
